### ISSUE TITLE
Logo for Steem-editor

### ISSUE THREAD

**Issue by loydjayme25** [ety001/steem-editor#14]
can i submit my logo design for this project ?

**Comment by ety001** [comment]
This is welcome :)

**Comment by loydjayme25** [comment]
okay thanks sir ! ill do my best.

**Comment by loydjayme25** [comment]
![editorsample](https://user-images.githubusercontent.com/37318022/38564968-c18a2a28-3d12-11e8-8608-df4be2836121.png)
S stands for Steem
E for Editor
and paint brush as the common tool for making an art

**Comment by loydjayme25** [comment]
im open for suggestions sir

**Comment by ety001** [comment]
Thank you for your job. I'm afraid this is not my want. But I can't tell where there are problems.

**Comment by ety001** [comment]
I think I still keep the current logo.
![steem-editor](https://user-images.githubusercontent.com/801928/38595548-123ffe2c-3d7f-11e8-84ca-82e2cad097e1.png)
